export const essay = `### The Art of the Placeholder: A Perfectly Adequate Essay on Absolutely Nothing in Particular

In an era defined by relentless productivity, endless content creation, and the ceaseless demand for original thought, the placeholder essay emerges as a quiet act of rebellion. It is the literary equivalent of leaving a sticky note on an empty fridge that reads “Milk (eventually).” It says, without saying much at all, “I was here, I intended to do something, and that intention should count for something.” This essay, dear reader, is precisely that: a placeholder. A space-holder. A five-paragraph monument to the noble art of buying time.

The first virtue of the placeholder essay is its honesty. While other essays pretend to illuminate the human condition, dissect climate policy, or finally settle whether pineapple belongs on pizza, the placeholder makes no such pretense. It admits upfront that its author is currently distracted by YouTube essays about abandoned malls, a group chat that won’t stop blowing up, or the existential dread of having seventeen open browser tabs. In this transparency, the placeholder achieves a rare moral purity unattainable by its more ambitious cousins.

Secondly, placeholder essays are remarkably efficient. A traditional 1,500-word paper on, say, the socioeconomic implications of late-stage capitalism might require research, citations, and at least the illusion of caring. A placeholder essay requires only the vague memory of middle-school essay structure and a functioning copy-paste function. Five paragraphs, an introduction with a thesis that gestures vaguely toward meaning, three body paragraphs that circle the same point like tired goldfish, and a conclusion that restates the thesis as though anyone had forgotten it four minutes later: perfection, achieved in under ten minutes.

Moreover, placeholder essays serve an important ecological function. Every time a student submits one, somewhere a tree breathes a sigh of relief. The rainforests of academic integrity may be under threat, but the rainforests of actual trees are quietly thriving thanks to bullet points, 1.5-line spacing, and 14-point Garamond (which is basically 12-point wearing a fake mustache).

In conclusion, the placeholder essay is not merely a procrastination tool; it is a mirror reflecting the modern soul (distracted, overwhelmed, yet still capable of producing 400 words that look suspiciously like effort). It reminds us that sometimes “good enough” is not a surrender but a strategy, that deadlines are more like suggestions with consequences, and that the gap between intention and execution is where most of human life actually happens. This essay has fulfilled its sacred duty: it has taken up space, met a minimum word count, and delayed real work for another day.

Thank you for reading this entirely real and definitely not hastily written essay. Please ignore any typos they add character.`;
